# Generated by Django 5.2.15 on 2026-06-20 10:57

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_remove_staticpage_snippet"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlexiblePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 1),
                            ("paragraph", 2),
                            ("image", 5),
                            ("card_grid", 13),
                            ("button", 16),
                            ("video", 17),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Texte du titre", "max_length": 255},
                            ),
                            1: ("wagtail.blocks.StructBlock", [[("text", 0)]], {}),
                            2: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "icon": "pilcrow",
                                    "label": "Texte riche",
                                    "template": "home/blocks/paragraph_block.html",
                                },
                            ),
                            3: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Image"},
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Légende",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 3), ("caption", 4)]],
                                {},
                            ),
                            6: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "help_text": "Choisie parmi les images du site.",
                                    "label": "Image",
                                },
                            ),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Titre", "max_length": 120},
                            ),
                            8: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Sous-titre",
                                    "max_length": 160,
                                    "required": False,
                                },
                            ),
                            9: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Description", "required": False},
                            ),
                            10: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Optionnel : rend la carte entière cliquable vers cette page du site.",
                                    "label": "Lien vers une page",
                                    "required": False,
                                },
                            ),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("image", 6),
                                        ("title", 7),
                                        ("subtitle", 8),
                                        ("description", 9),
                                        ("link_page", 10),
                                    ]
                                ],
                                {},
                            ),
                            12: (
                                "wagtail.blocks.ListBlock",
                                (11,),
                                {"label": "Cartes", "min_num": 1},
                            ),
                            13: ("wagtail.blocks.StructBlock", [[("cards", 12)]], {}),
                            14: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Libellé", "max_length": 80},
                            ),
                            15: ("wagtail.blocks.URLBlock", (), {"label": "Lien"}),
                            16: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 14), ("url", 15)]],
                                {},
                            ),
                            17: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {
                                    "icon": "media",
                                    "label": "Vidéo (Vimeo, YouTube…)",
                                    "template": "home/blocks/video_block.html",
                                },
                            ),
                        },
                        help_text="Empilez les blocs souhaités, dans l'ordre voulu.",
                        verbose_name="Contenu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page flexible",
                "verbose_name_plural": "Pages flexibles",
            },
            bases=("wagtailcore.page",),
        ),
    ]
