# Generated by Django 5.2.15 on 2026-06-21 08:08

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_alter_flexiblepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flexiblepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 1),
                    ("paragraph", 2),
                    ("image", 5),
                    ("card_grid", 13),
                    ("interactive_list", 19),
                    ("button", 22),
                    ("video", 23),
                    ("hosted_video", 25),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Texte du titre", "max_length": 255},
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("text", 0)]], {}),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "icon": "pilcrow",
                            "label": "Texte riche",
                            "template": "home/blocks/paragraph_block.html",
                        },
                    ),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image"},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Légende", "max_length": 255, "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 3), ("caption", 4)]],
                        {},
                    ),
                    6: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Choisie parmi les images du site.",
                            "label": "Image",
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Titre", "max_length": 120},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sous-titre", "max_length": 160, "required": False},
                    ),
                    9: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Description", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Optionnel : rend la carte entière cliquable vers cette page du site.",
                            "label": "Lien vers une page",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 6),
                                ("title", 7),
                                ("subtitle", 8),
                                ("description", 9),
                                ("link_page", 10),
                            ]
                        ],
                        {},
                    ),
                    12: (
                        "wagtail.blocks.ListBlock",
                        (11,),
                        {"label": "Cartes", "min_num": 1},
                    ),
                    13: ("wagtail.blocks.StructBlock", [[("cards", 12)]], {}),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sous-titre", "max_length": 200, "required": False},
                    ),
                    15: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Contenu détaillé", "required": False},
                    ),
                    16: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Optionnel : rend l'item cliquable vers cette page du site.",
                            "label": "Lien vers une page",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 7),
                                ("subtitle", 14),
                                ("content", 15),
                                ("link_page", 16),
                            ]
                        ],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.ListBlock",
                        (17,),
                        {"label": "Items", "min_num": 1},
                    ),
                    19: ("wagtail.blocks.StructBlock", [[("items", 18)]], {}),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Libellé", "max_length": 80},
                    ),
                    21: ("wagtail.blocks.URLBlock", (), {"label": "Lien"}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 20), ("url", 21)]],
                        {},
                    ),
                    23: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "icon": "media",
                            "label": "Vidéo (Vimeo, YouTube…)",
                            "template": "home/blocks/video_block.html",
                        },
                    ),
                    24: (
                        "wagtailmedia.blocks.VideoChooserBlock",
                        (),
                        {"label": "Fichier vidéo"},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("video", 24), ("caption", 4)]],
                        {},
                    ),
                },
                help_text="Empilez les blocs souhaités, dans l'ordre voulu.",
                verbose_name="Contenu",
            ),
        ),
    ]
