# Generated by Django 5.2.15 on 2026-06-21 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_flexiblepage_body'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexiblepage',
            name='banner',
            field=models.ForeignKey(blank=True, help_text="Optionnel : image affichée en fond de l'en-tête de la page.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Bannière'),
        ),
    ]
