# Generated by Django 5.2.12 on 2026-04-15 11:17

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='credits',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Crédits'),
        ),
        migrations.AddField(
            model_name='project',
            name='video_duration',
            field=models.CharField(blank=True, max_length=50, verbose_name='Durée de la vidéo'),
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.CharField(blank=True, max_length=20, verbose_name='Année de création'),
        ),
    ]
