# Generated by Django 5.2.15 on 2026-06-15 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_remove_project_snippet"),
        # La sélection existante est d'abord reportée vers FeaturedProject.
        ("home", "0012_seed_featured_projects"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectpage",
            name="featured",
        ),
    ]
