# Generated by Django 5.2.15 on 2026-06-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_seed_home_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Création et Production de contenus audiovisuels à Lille : documentaires, clips, captations et contenus dans les Hauts-de-France', help_text='Texte de description affiché sous le titre principal.', verbose_name='Sous-titre'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default="Cultur'all", help_text="Titre affiché en grand sur la vidéo d'accueil.", max_length=255, verbose_name='Titre principal'),
        ),
    ]
