# Generated by Django 5.2.15 on 2026-06-12 19:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_hero_subtitle_homepage_hero_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='custom_section',
            field=wagtail.fields.StreamField([('heading', 1), ('paragraph', 2), ('image', 5), ('button', 8), ('video', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Texte du titre', 'max_length': 255}), 1: ('wagtail.blocks.StructBlock', [[('text', 0)]], {}), 2: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Texte riche', 'template': 'home/blocks/paragraph_block.html'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Légende', 'max_length': 255, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 3), ('caption', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Libellé', 'max_length': 80}), 7: ('wagtail.blocks.URLBlock', (), {'label': 'Lien'}), 8: ('wagtail.blocks.StructBlock', [[('text', 6), ('url', 7)]], {}), 9: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media', 'label': 'Vidéo (Vimeo, YouTube…)', 'template': 'home/blocks/video_block.html'})}, help_text="Zone libre affichée sous la section « Notre Réseau ». Ajoutez les blocs souhaités, dans l'ordre voulu.", verbose_name='Section personnalisable'),
        ),
    ]
