# Generated by Django 5.2.15 on 2026-06-12 19:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homepage_custom_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='custom_section',
            field=wagtail.fields.StreamField([('heading', 1), ('paragraph', 2), ('image', 5), ('card_grid', 12), ('button', 15), ('video', 16)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Texte du titre', 'max_length': 255}), 1: ('wagtail.blocks.StructBlock', [[('text', 0)]], {}), 2: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Texte riche', 'template': 'home/blocks/paragraph_block.html'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Légende', 'max_length': 255, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 3), ('caption', 4)]], {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Choisie parmi les images du site.', 'label': 'Image'}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Titre', 'max_length': 120}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Sous-titre', 'max_length': 160, 'required': False}), 9: ('wagtail.blocks.TextBlock', (), {'label': 'Description', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('image', 6), ('title', 7), ('subtitle', 8), ('description', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'label': 'Cartes', 'min_num': 1}), 12: ('wagtail.blocks.StructBlock', [[('cards', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'label': 'Libellé', 'max_length': 80}), 14: ('wagtail.blocks.URLBlock', (), {'label': 'Lien'}), 15: ('wagtail.blocks.StructBlock', [[('text', 13), ('url', 14)]], {}), 16: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media', 'label': 'Vidéo (Vimeo, YouTube…)', 'template': 'home/blocks/video_block.html'})}, help_text="Zone libre affichée sous la section « Notre Réseau ». Ajoutez les blocs souhaités, dans l'ordre voulu.", verbose_name='Section personnalisable'),
        ),
    ]
