# Generated by Django 5.2.15 on 2026-06-15 12:10

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_seed_main_menu"),
        # Avant la suppression du champ `featured` : la data migration 0012
        # doit pouvoir lire `featured` pour reporter la sélection existante.
        ("projects", "0008_remove_project_snippet"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="featured_projects_title",
            field=models.CharField(
                default="Les projets à la une",
                help_text="Titre affiché au-dessus des projets mis en avant.",
                max_length=255,
                verbose_name="Titre de la section projets",
            ),
        ),
        migrations.CreateModel(
            name="FeaturedProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_projects",
                        to="home.homepage",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="projects.projectpage",
                        verbose_name="Projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projet à la une",
                "verbose_name_plural": "Projets à la une",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
