# Generated by Django 5.2.15 on 2026-06-23 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_homepage_custom_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='featured_projects_title',
        ),
        migrations.DeleteModel(
            name='FeaturedProject',
        ),
    ]
